### ISSUE TITLE
Should Event Be called Condvar?

### ISSUE THREAD

**Issue by zicklag** [stjepang/piper#9]
I'm not necessarily convinced it should be changed, but would it make sense to call `Event` `Condvar`  instead to help people know just from the name what it does? Because it is essentially just an async `Condvar` isn't it? Are there any differences from a `Condvar`?

Again, not that `Event` is even a bad name for it, I just thought about it and figured it'd be good to see what others thought.

**Comment by zicklag** [comment]
After reading docs for Event, I'm kind of liking the name because of the Event/listen terminology which is easy to think about where Condvar in the Rust standard library documentation was actually a little confusing at first.

**Comment by stjepang** [comment]
Hard to invent a familiar name because it's not quite a condvar, although it shares similarities with it. It is probably most similar to an eventcount, but it's not quite that either. And eventcounts are a bit obscure. Tokio has a similar thing called `Notify` - which is kind of like crossbeam's `Parker` for futures.

 I personally find condvars pretty unintuitive - they always need to be paired with a mutex, and it's non-obvious what the condition and what the variable there is. It just feels like a very strange name to me :)

So I picked a slightly generic name, `Event`. I felt this primitive is really about events, where an event can be "a message was pushed into a channel", or "a mutex was unlocked", etc. And the API allows you to listen for events and to trigger events.

Anyways, naming is hard. :)

**Comment by zicklag** [comment]
Hardest thing in programming right? :wink:

Anyway, I think it's good. :+1:
